# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'broker_settings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 325)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.host_le = QtWidgets.QLineEdit(self.centralwidget)
        self.host_le.setGeometry(QtCore.QRect(140, 70, 181, 21))
        self.host_le.setObjectName("host_le")
        self.host_l = QtWidgets.QLabel(self.centralwidget)
        self.host_l.setGeometry(QtCore.QRect(40, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.host_l.setFont(font)
        self.host_l.setAlignment(QtCore.Qt.AlignCenter)
        self.host_l.setObjectName("host_l")
        self.port_le = QtWidgets.QLineEdit(self.centralwidget)
        self.port_le.setGeometry(QtCore.QRect(140, 100, 181, 21))
        self.port_le.setObjectName("port_le")
        self.port_l = QtWidgets.QLabel(self.centralwidget)
        self.port_l.setGeometry(QtCore.QRect(40, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.port_l.setFont(font)
        self.port_l.setAlignment(QtCore.Qt.AlignCenter)
        self.port_l.setObjectName("port_l")
        self.username_le = QtWidgets.QLineEdit(self.centralwidget)
        self.username_le.setGeometry(QtCore.QRect(140, 130, 181, 21))
        self.username_le.setObjectName("username_le")
        self.username_l = QtWidgets.QLabel(self.centralwidget)
        self.username_l.setGeometry(QtCore.QRect(40, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.username_l.setFont(font)
        self.username_l.setAlignment(QtCore.Qt.AlignCenter)
        self.username_l.setObjectName("username_l")
        self.password_le = QtWidgets.QLineEdit(self.centralwidget)
        self.password_le.setGeometry(QtCore.QRect(140, 160, 181, 21))
        self.password_le.setText("")
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_le.setObjectName("password_le")
        self.password_l = QtWidgets.QLabel(self.centralwidget)
        self.password_l.setGeometry(QtCore.QRect(40, 160, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.password_l.setFont(font)
        self.password_l.setAlignment(QtCore.Qt.AlignCenter)
        self.password_l.setObjectName("password_l")
        self.topic_name_le = QtWidgets.QLineEdit(self.centralwidget)
        self.topic_name_le.setGeometry(QtCore.QRect(140, 190, 181, 21))
        self.topic_name_le.setObjectName("topic_name_le")
        self.topic_name_l = QtWidgets.QLabel(self.centralwidget)
        self.topic_name_l.setGeometry(QtCore.QRect(40, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.topic_name_l.setFont(font)
        self.topic_name_l.setAlignment(QtCore.Qt.AlignCenter)
        self.topic_name_l.setObjectName("topic_name_l")
        self.title_l = QtWidgets.QLabel(self.centralwidget)
        self.title_l.setGeometry(QtCore.QRect(40, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.title_l.setFont(font)
        self.title_l.setAlignment(QtCore.Qt.AlignCenter)
        self.title_l.setObjectName("title_l")
        self.create_conf_file_pb = QtWidgets.QPushButton(self.centralwidget)
        self.create_conf_file_pb.setGeometry(QtCore.QRect(140, 240, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.create_conf_file_pb.setFont(font)
        self.create_conf_file_pb.setObjectName("create_conf_file_pb")
        self.quit_pb = QtWidgets.QPushButton(self.centralwidget)
        self.quit_pb.setGeometry(QtCore.QRect(290, 280, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.quit_pb.setFont(font)
        self.quit_pb.setObjectName("quit_pb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.host_l.setText(_translate("MainWindow", "host"))
        self.port_l.setText(_translate("MainWindow", "port"))
        self.username_l.setText(_translate("MainWindow", "username"))
        self.password_l.setText(_translate("MainWindow", "password"))
        self.topic_name_l.setText(_translate("MainWindow", "topic_name"))
        self.title_l.setText(_translate("MainWindow", "Please insert your broker settings:"))
        self.create_conf_file_pb.setText(_translate("MainWindow", "create conf file"))
        self.quit_pb.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

